# Generated by Django 3.1.13 on 2021-08-11 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_good_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerdoc', models.CharField(max_length=20, verbose_name='Номер документв')),
                ('datadoc', models.DateField(verbose_name='Дата документа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Создан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлен')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.dealer', verbose_name='Поставщик')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.operation', verbose_name='Вид документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['datadoc'],
            },
        ),
    ]
