# Generated by Django 3.1.13 on 2021-08-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20210811_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['title'], 'verbose_name': 'Фамилия,Имя,Отчество', 'verbose_name_plural': 'Фамилия,Имя,Отчество'},
        ),
    ]
