# Generated by Django 3.1.13 on 2021-08-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20210816_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['title'], 'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы'},
        ),
        migrations.RemoveField(
            model_name='good',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Фамилия,Имя,Отчество'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Единица измерения'),
        ),
    ]
