# Generated by Django 3.1.13 on 2021-08-19 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20210819_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='trade.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
