# Generated by Django 3.1.13 on 2021-08-30 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_good_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='transaction',
            field=models.BooleanField(default=False, verbose_name='Проведен'),
        ),
        migrations.AddField(
            model_name='docjurnal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 30, 7, 59, 50, 608492, tzinfo=utc), verbose_name='Обновлен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docjurnal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Создан'),
        ),
    ]
