# Generated by Django 3.1.13 on 2021-09-06 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20210830_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.dealer', verbose_name='Поставщик'),
        ),
    ]
