# Generated by Django 3.1.13 on 2021-09-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20210906_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.RemoveField(
            model_name='doc',
            name='operation',
        ),
    ]
