# Generated by Django 3.1.13 on 2021-09-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AddField(
            model_name='docjurnal',
            name='unit',
            field=models.CharField(default='', max_length=20, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
