# Generated by Django 3.1.13 on 2021-09-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_auto_20210915_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='typedoc',
            field=models.IntegerField(default=1, verbose_name='Тип документа'),
            preserve_default=False,
        ),
    ]
