# Generated by Django 3.1.13 on 2021-09-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_doc_typedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='typedoc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Тип документа'),
        ),
    ]
