# Generated by Django 3.1.13 on 2021-09-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_auto_20210917_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='typedoc',
            field=models.IntegerField(default=0, verbose_name='Тип документа'),
        ),
    ]
